-- Active: 1784723522577@@localhost@5432@kioskvisit
CREATE TABLE Tokens(
    TokenId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TokenNo VARCHAR(20) UNIQUE,
    VisitId INT NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_VisitId
        FOREIGN KEY (VisitId) 
        REFERENCES Visits(VisitId)

);

select * from Tokens

drop table Tokens CASCADE