-- Active: 1784723522577@@localhost@5432@queuekiosk
CREATE TABLE Token(
    TokenId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TokenNo VARCHAR(20) UNIQUE,
    VisitId INT NOT NULL,
<<<<<<< HEAD
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    CONSTRAINT fk_VisitID 
=======
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_VisitId
>>>>>>> 201874d44ee97f316f9cd555777ede2e3bb35cd2
        FOREIGN KEY (VisitId) 
        REFERENCES Visits(VisitId)


    
);


<<<<<<< HEAD





=======
drop table Token
>>>>>>> 201874d44ee97f316f9cd555777ede2e3bb35cd2
