CREATE TABLE Visits
(
    VisitId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VisitNo TEXT NOT NULL,
    PatientId INT NOT NULL,
    MedicalServicesCode TEXT NOT NULL,
    VisitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   
    CONSTRAINT fk_patient 
        FOREIGN KEY (PatientId) 
        REFERENCES Patients(PatientId)
    
);