-- Active: 1784723522577@@localhost@5432@kioskvisit
CREATE TABLE Patients(
    PatientId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PatientNo TEXT NOT NULL,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Gender CHAR NOT NULL,
    Contact TEXT ,
    Address TEXT NOT NULL,
    CreatedAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 

);



INSERT INTO patients
(
    patientno,
    firstname,
    lastname,
    gender,
    Address,
    contact
)
VALUES
(
    '26001',
    'Peace',
    'Isaac',
    'F',
    'GAYAZA',
    '070008888'
),
(
    '26002',
    'Emmanuel',
    'Grace',
    'M',
    'Kima',
    '077777700'
),
(
    '26003',
    'jese',
    'Mugisa',
    'M',
    'Kamuli',
    '0700000090'
),(
    '26004',
    'Othman',
    'kimweri',
    'M',
    'Isingiro',
    '0700000000'
)

select * From patients

select * from Medicalservices

SELECT *
FROM MedicalServices
LIMIT 1;