-- Active: 1784723522577@@localhost@5432@kioskvisit
CREATE TABLE Patients(
    PatientId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PatientNo TEXT NOT NULL,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Gender CHAR NOT NULL,
    Contact TEXT ,
    Address TEXT NOT NULL,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP 

)
--checking for the existence of all the tables
select * from patients;
select * from tokens;
select * from medicalservices;
select * from visits